#!/usr/bin/env python3
import argparse
import re


def _sanitize_id(s: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", s).strip("_") or "node"


def generate_mermaid(project_name: str, nodes: list, sensors: list) -> str:
    proj_id = _sanitize_id(project_name)
    cloud_id = f"{proj_id}_Cloud"
    mermaid = (
        f"flowchart TD\n"
        f"    subgraph {cloud_id} [\"{project_name} Cloud\"]\n"
        f"        Brain[\"Mema Core / FastAPI\"]\n"
        f"        DB[(\"SQLite/Redis\")]\n"
        f"        Brain --- DB\n"
        f"    end\n\n"
    )
    for node in nodes:
        node_id = _sanitize_id(node)
        mermaid += f"    {node_id}[\"{node}\"] --- Brain\n"
        for sensor in sensors:
            sens_id = _sanitize_id(sensor)
            mermaid += f"    {node_id} --- {node_id}_{sens_id}[\"{sensor}\"]\n"
    return mermaid


def generate_cpp_config(project_name: str, node_id: str) -> str:
    safe_node = re.sub(r"[^a-zA-Z0-9_-]", "_", node_id)
    return f"""// --- {project_name} | Node Configuration ---
// Generated by Mema IoT Architect
// WiFi/MQTT credentials: use secrets.h (copy from assets/templates/esp32/secrets.h.example)

#include "secrets.h"

#define DEVICE_ID       "{safe_node}"

// Topic Mapping
#define TOPIC_STATE     "devices/{safe_node}/all/state"
#define TOPIC_SET       "devices/{safe_node}/+/set"
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Mema IoT Architect Tool")
    parser.add_argument("--project", default="Generic IoT")
    parser.add_argument("--nodes", default="esp32-node")
    parser.add_argument("--sensors", default="dht22")

    args = parser.parse_args()

    nodes_list = [n.strip() for n in args.nodes.split(",")]
    sensors_list = [s.strip() for s in args.sensors.split(",")]

    print(f"--- PROJECT: {args.project} ---")
    print("\n[Architecture Diagram (Mermaid)]")
    print(generate_mermaid(args.project, nodes_list, sensors_list))

    print("\n[Firmware Configuration (First Node)]")
    print(generate_cpp_config(args.project, nodes_list[0]))
