import argparse
import json
import os

def generate_mermaid(project_name, nodes, sensors):
    mermaid = f"graph TD\n    subgraph {project_name}_Cloud\n        Brain[Mema Core / FastAPI]\n        DB[(SQLite/Redis)]\n        Brain --- DB\n    end\n\n"
    
    for node in nodes:
        mermaid += f"    {node}[{node}] --- Brain\n"
        for sensor in sensors:
            mermaid += f"    {node} --- {node}_{sensor}[{sensor}]\n"
            
    return mermaid

def generate_cpp_config(project_name, node_id):
    return f"""
// --- {project_name} | Node Configuration ---
// Generated by Mema IoT Architect

#define WIFI_SSID       "YOUR_SSID"
#define WIFI_PASS       "YOUR_PASS"
#define MQTT_SERVER     "iot.glassgallery.my.id"
#define DEVICE_ID       "{node_id}"

// Topic Mapping
#define TOPIC_STATE     "devices/{node_id}/all/state"
#define TOPIC_SET       "devices/{node_id}/+/set"
"""

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Mema IoT Architect Tool")
    parser.add_argument("--project", default="Generic IoT")
    parser.add_argument("--nodes", default="esp32-node")
    parser.add_argument("--sensors", default="dht22")
    
    args = parser.parse_args()
    
    nodes_list = [n.strip() for n in args.nodes.split(",")]
    sensors_list = [s.strip() for s in args.sensors.split(",")]
    
    print(f"--- PROJECT: {args.project} ---")
    print("\n[Architecture Diagram (Mermaid)]")
    print(generate_mermaid(args.project, nodes_list, sensors_list))
    
    print("\n[Firmware Configuration (First Node)]")
    print(generate_cpp_config(args.project, nodes_list[0]))
